spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance-db
    username: vernon
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.mattemat.finance:
      client:
        CurrencyAPIClient: error